# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c9dcc8b6c73d5f241c08400d0968e257ce142e4940a0ca15834ac09a2e82dff8a0d03e05d1e5a5f14b8bcdee30e5e31001dc6cac491ed4e58f42a0059321cf7c

test:
  secret_key_base: 32c9748d4fd6752d5b86f28af5eba56a252e17ef74f86bc87a2197c05928111e4ca2c710ab8e71f29654d1336d9d5e81c5400025fb92417e74a03dc3e4f1f227

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
